Private Sub Pedidos_List_Click()

End Sub

Private Sub Pedidos_Paginador_Change()
    
End Sub

Private Sub Pedidos_Paginador_LostFocus()
    CRUD_Read
End Sub

Private Sub Pesquisa_GotFocus()
    TxtFormat_Focus
End Sub
Private Sub Pesquisa_LostFocus()
    TxtFormat_LostFocus
End Sub
Private Sub Txt1_GotFocus()
    TxtFormat_Focus
End Sub

Private Sub Txt1_LostFocus()
    TxtFormat_LostFocus
End Sub